# site properties and page defaults
title: Forecasting and Surveillance of Infectious Threats and Epidemics (ForeSITE)
subtitle: An Insight Net Center for Integration
description: ForeSITE is a CDC Center for Integration in the Center for Forecasting and Outbreak Analytics Insight Net. The goal of ForeSITE is to 1) work collaboratively with local and state health departments and healthcare organizations to implement and iteratively refine tools for outbreak analytics and infectious disease modeling; 2) evaluate the usability and usefulness of these analytic and modeling tools for public health and healthcare decision-making; 3) partner with CDC and other Centers in the CFA Centers for Outbreak Analytics and Disease Modeling Network to enhance national capability to respond to infectious disease threats and public health emergencies.
header: images/Snow_Mountains.png
footer: images/Snow_Mountains.png
proofer: false

# site social media and other links
links:
  email: contact@EpiForeSITEDESCRIPTION=An engaging 1-3 sentence description of your lab..com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: EpiForeSITEDESCRIPTION=An engaging 1-3 sentence description of your lab.
  twitter: EpiForeSITEDESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: EpiForeSITEDESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
